version: '3.9'

services:
  db:
    image: postgres:17
    container_name: ecomap_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomap
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecomap_backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
